version: "2.15.1"

services:
  api:
    container_name: api_rest
    restart: always
    build: .
    ports:
      - "4000:3000"
    links:
        - mongodb
    volumes:
      - .:/usr/src/app
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27018:27017"
    command: mongod --quiet --logpath /dev/null
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
